services:
  web1:
    build: ./web1-flask
    container_name: web1
    ports:
      - "8081:80"
    networks:
      - lab-net

  web2:
    build: ./web2-nginx
    container_name: web2
    ports:
      - "8082:80"
    networks:
      - lab-net

  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - lab-net

networks:
  lab-net:
    driver: bridge
