version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: sqli_xss_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: elconfidencial
      MYSQL_USER: vulnuser
      MYSQL_PASSWORD: vulnpass
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: ./web
    container_name: sqli_xss_web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./web/src:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sqli_xss_pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
